# Generated by Django 4.0.6 on 2024-04-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='win',
            field=models.IntegerField(default=10),
        ),
    ]
